name: Dockle

on:
  push:
    branches:
      - master
      - develop
      - develop-mame
  pull_request:

permissions: {}

jobs:
  dockle:
    if: ${{ false }}

    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      DOCKER_CONTENT_TRUST: 1
      DOCKLE_VERSION: 0.4.14

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Download and install dockle v${{ env.DOCKLE_VERSION }}
        run: |
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v${DOCKLE_VERSION}/dockle_${DOCKLE_VERSION}_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
      - name: Copy config files
        run: |
          cp .config/docker_example.env .config/docker.env
          cp ./compose_example.yml ./compose.yml
      - name: Run container
        run: |
          docker compose up -d web
          docker tag "$(docker compose images web | awk 'OFS=":" {print $4}' | tail -n +2)" misskey-web:latest
      - name: Run dockle
        run: |
          cmd="dockle --exit-code 1 misskey-web:latest ${image_name}"
          echo "> ${cmd}"
          eval "${cmd}"
