name: Release

on:
  push:
    branches:
      - develop-mame

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-tags: true
          fetch-depth: 2

      - name: Save current version
        id: current_version
        run: echo "current_version=$(jq -r '.version | split("+")[0]' ./package.json)" >> $GITHUB_OUTPUT

      - name: Checkout previous commit
        run: git checkout HEAD^

      - name: Save version on previous commit
        id: previous_version
        run: echo "previous_version=$(jq -r '.version | split("+")[0]' ./package.json)" >> $GITHUB_OUTPUT

      - name: Checkout main branch
        run: git checkout $(git name-rev --name-only $(git reflog -n 1 --skip=1 --pretty='%H'))

      - name: Check if version changed
        id: version_changed
        run: |
          VERSION_CHANGED=$(if [ "$PREV_VER" == "$CURR_VER" ]; then echo false; else echo true; fi)
          echo "version_changed=$VERSION_CHANGED" >> $GITHUB_OUTPUT
        env:
          PREV_VER: ${{ steps.previous_version.outputs.previous_version }}
          CURR_VER: ${{ steps.current_version.outputs.current_version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install Corepack
        run: npm install -g corepack@latest

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check if lock file is not modified
        run: git diff --exit-code pnpm-lock.yaml

      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Note latest commit hash
        run: git rev-parse HEAD > ./built/hash

      - name: Archive (tar)
        run: tar -zcvf ./built.tar.gz ./built ./packages/misskey-js/built ./packages/backend/built

      - name: Get repository name
        id: repository-name
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Get GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ steps.repository-name.outputs.name }}

      # on version not changed
      - name: Remove existing edge release and tag
        if: ${{ steps.version_changed.outputs.version_changed == 'false' }}
        run: |
          gh release delete "edge" -y --cleanup-tag || true
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      # on version not changed
      - name: Create edge release
        if: ${{ steps.version_changed.outputs.version_changed == 'false' }}
        run: gh release create "edge" ./built.tar.gz --prerelease --generate-notes --notes-start-tag "$NOTES_START_TAG"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          NOTES_START_TAG: ${{ steps.current_version.outputs.current_version }}

      # on version changed
      - name: Create versioned release
        if: ${{ steps.version_changed.outputs.version_changed == 'true' }}
        run: gh release create "$TAG_NAME" ./built.tar.gz --latest --generate-notes --notes-start-tag "$NOTES_START_TAG"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          TAG_NAME: ${{ steps.current_version.outputs.current_version }}
          NOTES_START_TAG: ${{ steps.previous_version.outputs.previous_version }}
